xcodeproj 'RKIntentTests'
workspace '../RKIntent'

platform :ios, '7.0'

target :RKIntentTests do
  pod 'Expecta', '~> 0.2.3'
  pod 'Specta',  '~> 0.2.1'
  pod 'OCMock',  '~> 2.2'
  pod 'RKIntent', :path => '../'
end
