//  Copyright (c) 2014 rokob. All rights reserved.

#import <Foundation/Foundation.h>
#import <dispatch/queue.h>

@protocol RKIntent;
@protocol RKIntentHandler;

/**
 The source of an intent
 */
@interface RKIntentSource : NSObject

/**
 The designated initializer. This object encapsulates a source of intents to perform actions.
 
 @param identifier An identifier that identifies the source. How this is used (if at all) is up to a specific handler.
 @param callbackQueue This must not be NULL if either the successBlock or failureBlock is set. All callback blocks will
    be executed on this queue.
 @param successBlock This can be nil; called with an intent and handler upon successful handling of the intent.
 @param failureBlock This can be nil; called with an intent that was generated by this source but could not be handled.
 */
- (instancetype)initWithIdentifier:(NSString *)identifier
                     callbackQueue:(dispatch_queue_t)callbackQueue
                      successBlock:(void(^)(id<RKIntent>, id<RKIntentHandler>))successBlock
                      failureBlock:(void(^)(id<RKIntent>))failureBlock;

@property (nonatomic, readonly, copy) NSString *identifier;

/**
 Should be called by an intent handler upon successfully handling an intent.
 */
- (void)didHandleIntent:(id<RKIntent>)intent withHandler:(id<RKIntentHandler>)handler;

/**
 Should be called by an intent handler when it fails to handle an intent.
 */
- (void)failedToHandleIntent:(id<RKIntent>)intent;

@end
